CREATE TABLE [dbo].[KuduTable]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KuduTable] ADD CONSTRAINT [PK_KuduTable] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
